services:
  api:
      build:
        context: .
        dockerfile: Dockerfile
      image: fastapi-starter
      volumes:
        - ./:/app
      mem_limit: 4096m        # 最大内存（对应limits）
      mem_reservation: 256m   # 预留内存256MB（对应reservations）
      ports:
        - "${APP_PORT:-8000}:8000"
      restart: unless-stopped
      # 开发环境
      command: >
        uv run uvicorn app.main:app 
        --host 0.0.0.0 
        --port 8000 
        --reload

      # 正式环境
#      command: >
#       uv run gunicorn app.main:app
#        -k uvicorn.workers.UvicornWorker
#        -w ${APP_WORKER:-3}
#        -b 0.0.0.0:8000
#        --max-requests 10000
#        --keep-alive 10

      networks:
        - docker-local #连接到自定义的网络

networks:
  docker-local:
    external: true  # 重要：使用外部已存在的网络
    